addReviewers: true

addAssignees: author

reviewers:
  - tmaxhr
  - tkdgh3050
  - LucetTin5

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
